server:
  port: 10501   # HTTP (Tomcat) port

eureka:
  instance:
    hostname: ms-geolocation-peer2
    metadataMap:
      instanceId:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
