spring:
  application:
    name: MS-Countries
  boot:
    admin:
      client:
        url:
        - http://spring-boot-admin:10100
  flyway:
    enabled: true
        
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
 
      
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
    platform: hsqldb
  data:
    rest:
      base-path: /api
  sleuth:
    web:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
logging:
  path: ./logs
  file: countries.log
  level:
    org.springframework: INFO
    org.flywaydb: INFO
    
server:
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  forward-headers-strategy: none
eureka:
  client:
    region: dev.gnc
    registerWithEureka: true

# ----------------------------------------------------------------------
# Profiles for multiple instances
# ----------------------------------------------------------------------
---
server:
  port: 10500   # HTTP (Tomcat) port
spring:
  profiles: peer1
  boot:
    admin:
      client:
        url:
          - http://spring-boot-admin:10100
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/
logging:
  file:
    path: ./logs
  level:
    org.springframework: INFO

---
server:
  port: 10501   # HTTP (Tomcat) port
spring:
  profiles: peer2
  boot:
    admin:
      client:
        url:
          - http://spring-boot-admin:10100
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  file:
    path: ./logs
  level:
    org.springframework: INFO
