server:
  port: 10500   # HTTP (Tomcat) port

eureka:
  instance:
    hostname: ms-geolocation-peer1
    metadataMap:
      instanceId:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/
