spring:
  application:
    name: geolocation
  boot:
    admin:
      client:
        url:
        - http://localhost:10100
  flyway:
    enabled: true
        
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
 
      
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
    platform: hsqldb
  data:
    rest:
      base-path: /api
  sleuth:
    web:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
logging:
  file: 
    path: "/var/log"
    name: ${spring.application.name}.log
  level:
    root: INFO 
   
server:
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  forward-headers-strategy: none

eureka:
  client:
    region: dev.gnc
    registerWithEureka: true
