spring:
  application:
    name: spring-cloud-gateway-server
  boot:
    admin:
      client:
        url:
          - http://spring-boot-admin:10100
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
  port: 10200

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: ./logs
  level:
    root: WARN 