spring:
  application:
    name: Spring Cloud Eureka Server
  boot:
    admin:
      client:
        url:
        - http://localhost:10100
        
server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

# ----------------------------------------------------------------------
# Profiles for multiple instances
# ----------------------------------------------------------------------
---
server:
  port: 10300   # HTTP (Tomcat) port
spring:
  profiles: peer1
  boot:
    admin:
      client:
        url:
          - http://localhost:10100  
eureka:
  instance:    
    hostname: localhost
    metadataMap:
      instanceId: 
  client:
    serviceUrl:
      defaultZone: http://localhost:10301/eureka/
logging:
  file:
    path: ./logs
  level:
    org.springframework: INFO      

---
server:
  port: 10301   # HTTP (Tomcat) port
spring:
  profiles: peer2
  boot:
    admin:
      client:
        url:
          - http://localhost:10100  
eureka:
  instance:    
    hostname: localhost
    metadataMap:
      instanceId: 
  client:
    serviceUrl:
      defaultZone: http://localhost:10300/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0  
logging:
  file:
    path: ./logs
  level:
    org.springframework: INFO    