spring:
  application:
    name: spring-cloud-eureka-server
  boot:
    admin:
      client:
        url:
        - http://spring-boot-admin:10100
        
server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

# ----------------------------------------------------------------------
# Profiles for multiple instances
# ----------------------------------------------------------------------
---
server:
  port: 10300   # HTTP (Tomcat) port
spring:
  profiles: peer1
  boot:
    admin:
      client:
        url:
          - http://spring-boot-admin:10100
eureka:
  instance:    
    hostname: spring-cloud-netflix-eureka-peer1
  client:
    registerWitEureka: false
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer2:10301/eureka/,http://spring-cloud-netflix-eureka-peer1:10300/eureka/

logging:
  file:
    path: ./logs
  level:
    org.springframework: WARN      

---
server:
  port: 10301   # HTTP (Tomcat) port
spring:
  profiles: peer2
  boot:
    admin:
      client:
        url:
          - http://spring-boot-admin:10100
eureka:
  instance:    
    hostname: spring-cloud-netflix-eureka-peer2
  client:
    registerWitEureka: false
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0  

logging:
  file:
    path: ./logs
  level:
    org.springframework: WARN    