spring:
  application:
    name: Spring Cloud Eureka Server
  boot:
    admin:
      url: http://localhost:10100
      api-path: api/applications
      hazelcast:
        enabled: false
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  use-forward-headers: true
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30        

# ----------------------------------------------------------------------
# Profiles for multiple instances
# ----------------------------------------------------------------------
---
server:
  port: 10300   # HTTP (Tomcat) port
spring:
  profiles: peer1
  boot:
    admin:
      client:
        service-url: http://localhost:10300
        management-url: http://localhost:10300
        health-url: http://localhost:10300/health  
eureka:
  instance:    
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:10301/eureka/
logging:
  path: ./logs
  file: eureka1.log
  level:
    org.springframework: INFO      

---
server:
  port: 10301   # HTTP (Tomcat) port
spring:
  profiles: peer2
  boot:
    admin:
      client:
        service-url: http://localhost:10301
        management-url: http://localhost:10301
        health-url: http://localhost:10301/health  
eureka:
  instance:    
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:10300/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0  
logging:
  path: ./logs
  file: eureka2.log
  level:
    org.springframework: INFO    