spring:
  application:
    name: Spring Cloud Eureka Server
  boot:
    admin:
      client:
        url:
        - http://localhost:10100
        
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics       

# ----------------------------------------------------------------------
# Profiles for multiple instances
# ----------------------------------------------------------------------
---
server:
  port: 10300   # HTTP (Tomcat) port
spring:
  profiles: peer1
  boot:
    admin:
      client:
        url:
          - http://localhost:10100  
eureka:
  instance:    
    hostname: localhost
    metadataMap:
      instanceId: 
  client:
    serviceUrl:
      defaultZone: http://localhost:10301/eureka/
logging:
  path: ./logs
  file: eureka1.log
  level:
    org.springframework: INFO      

---
server:
  port: 10301   # HTTP (Tomcat) port
spring:
  profiles: peer2
  boot:
    admin:
      client:
        url:
          - http://localhost:10100  
eureka:
  instance:    
    hostname: localhost
    metadataMap:
      instanceId: 
  client:
    serviceUrl:
      defaultZone: http://localhost:10300/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0  
logging:
  path: ./logs
  file: eureka2.log
  level:
    org.springframework: INFO    