spring:
  application:
    name: App-Client
  boot:
    admin:
      client:
        url:
        - http://localhost:10100
  flyway:
    enabled: true
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
    platform: hsqldb
  data:
    rest:
      base-path: /api
      
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
      
zuul:
  ignoredServices: '*'
  routes:
    countries: 
      path: /api/v1/countries/**
      serviceId: MS-Countries
      strip-prefix: false
      
 
logging:
  path: ./logs
  file: client.log
  level:
    org.springframework: INFO
    org.flywaydb: INFO
    
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  port: 10600
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10300/eureka/,http://localhost:10301/eureka/
    region: dev.gnc
    registerWithEureka: false 

