spring:
  application:
    name: App-Client
  boot:
    admin:
      client:
        url:
        - http://spring-boot-admin:10100
  flyway:
    enabled: true
    encoding: ISO-8859-1

  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

  datasource:
    url: jdbc:hsqldb:mem:testdb2
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
    platform: hsqldb
  data:
    rest:
      base-path: /api
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      
zuul:
  ignoredServices: '*'
  routes:
    countries: 
      path: /api/v1/countries/**
      serviceId: MS-Countries
      strip-prefix: false

logging:
  file:
    path: ./logs
  level:
    org.springframework: WARN
    org.flywaydb: WARN
    
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 10600
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-netflix-eureka-peer1:10300/eureka/,http://spring-cloud-netflix-eureka-peer2:10301/eureka/
    region: dev.gnc
    registerWithEureka: false 

