spring:
  application:
    name: spring-cloud-config-server
  boot:
    admin:
      client:
        url:
          - http://localhost:10100
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/DVanderstoken/configurations.git
          
server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
  port: 10800

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10300/eureka/,http://localhost:10301/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  
logging:
  file: 
    path: "/var/log"
    name: ${spring.application.name}.log
  level:
    root: INFO 
              