# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['prometheus:9090']

- job_name: spring-boot-admin
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['spring-boot-admin:10100']

- job_name: spring-cloud-gateway
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['spring-cloud-gateway:10200']

- job_name: spring-cloud-netflix-eureka
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['spring-cloud-netflix-eureka-peer1:10300','spring-cloud-netflix-eureka-peer2:10301']

- job_name: ms-geolocation
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['ms-geolocation-peer1:10500','ms-geolocation-peer2:10501']

- job_name: spring-cloud-config
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['spring-cloud-config:10800']
    