FROM bellsoft/liberica-openjdk-alpine:17-cds
ARG JAR_FILE=target/spring-ms-countries-*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 10500
ENTRYPOINT ["java", "-Dspring.profiles.active=default,dockerpeer1", "-jar", "/app.jar"]