FROM bellsoft/liberica-openjdk-alpine:17-cds
ARG JAR_FILE=target/spring-cloud-netflix-eureka-*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 10300
ENTRYPOINT ["java", "-Dspring.profiles.active=default,dockerpeer1", "-jar", "/app.jar"]