FROM bellsoft/liberica-openjdk-alpine:17-cds
ARG JAR_FILE=target/spring-cloud-netflix-eureka-*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 10301
ENTRYPOINT ["java", "-Dspring.profiles.active=default,dockerpeer2", "-jar", "/app.jar"]