spring:
  application:
    name: spring-boot-admin Server
  boot:
    admin:
      url: http://localhost:10100
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,heapdump,loggers,auditevents,hystrix.stream
    
server:
  port: 10100
   
management:
  security:
    enabled: false