spring:
  application:
    name: spring-boot-admin-server
  boot:    admin:      ui:        cache-templates: true
  
server:
  port: 10100
   
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: ./logs
  level:
    root: INFO 
