spring:
  application:
    name: spring-boot-admin Server
  boot:
    admin:
      client:
        url:
        - http://localhost:10100
    
server:
  port: 10100
   
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
